spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernete:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true