spring:
  datasource:
    url: jdbc:mysql://localhost:8080/School-Jess
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernete:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true